AEBSystem/AEBSystem.WebUI/Controllers/TRTrackingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AEBSystem.Core.Models;
using AEBSystem.Core.ViewModels;
using CrystalDecisions.CrystalReports.Engine;
using AEBSystem.DataAccess.InMemory;
using AEBSystem.DataAccess.SQL;

namespace AEBSystem.WebUI.Controllers
{
    public class TRTrackingController : Controller
    {

        // GET: TRTracking
        CAAPDATA_MNL_DbSet db_mnl = new CAAPDATA_MNL_DbSet();
        CAAPDATA_NLA_DbSet db_nla = new CAAPDATA_NLA_DbSet();
        CAAPDATA_MA_DbSet db_ma = new CAAPDATA_MA_DbSet();
        CAAPDATA_VA_DbSet db_va = new CAAPDATA_VA_DbSet();   


       

        public ActionResult Index(string search)
        {
            var username = Session["Username"].ToString();
            if (username == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var AirmenFromSP = db_mnl.getAirmen_all(search).ToList();
            return View(AirmenFromSP);
        }

        public ActionResult ExamHistory(string PEL, int amType)
        {
            List<ExamHistoryResult> history = new List<ExamHistoryResult>();
            history = db_mnl.ExamHistory(PEL, amType).ToList();

            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/CrystalReports"), "ExamHistory.rpt"));

            rd.SetDataSource(history);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", PEL + "_" + amType + "_History.pdf");
        }

        public ActionResult ViewApplications(string search)
        {
            var am = db_mnl.getAirmen_all(search).ToList();
            var tr = db_mnl.tblTestReportApplications.ToList();
            var lic = db_mnl.tblAMTypes.ToList();

            var viewModel = (from t in tr
                             join a in am on t.PEL equals a.PEL
                             join l in lic on t.amType equals l.code
                             where a.AirmenType.Equals(t.amType)
                             orderby t.Id descending
                             select new TestReportStatusViewModel
                             {
                                 Id = t.Id,
                                 PEL = t.PEL,
                                 Fullname = a.Fullname,
                                 License = l.description,
                                 Status = t.Status,
                                 Remarks = t.Remarks,
                                 ClaimedBy = t.ClaimedBy,
                                 ControlNo = t.ControlNo,
                                 BatchNo = t.BatchNo,
                                 LastModifiedBy = t.LastModifiedBy
                             }
                             ).ToList();
            return View(viewModel);
        }

        public ActionResult Initial(int Id, string Loc)
        {
            var username = Session["Username"].ToString();

            if (username == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (Loc == "MNL")
            {
                var am = db_mnl.tblAirmen.ToList();
                var lic = db_mnl.tblAMTypes.ToList();
                var tr = (from a in am
                          join l in lic on a.AirmenType_Id equals l.code
                          where a.Code.Equals(Id)
                          select new TestReportStatusViewModel
                          {
                              Id = a.Code,
                              PEL = a.PEL,
                              Fullname = a.Description,
                              amType = a.AirmenType_Id,
                              License = l.description
                          }).FirstOrDefault();
                return View(tr);
            }
            else if (Loc == "NLA")
            {
                var am = db_nla.tblAirmen.ToList();
                var lic = db_mnl.tblAMTypes.ToList();
                var tr = (from a in am
                          join l in lic on a.AirmenType_Id equals l.code
                          where a.Code.Equals(Id)
                          select new TestReportStatusViewModel
                          {
                              Id = a.Code,
                              PEL = a.PEL,
                              Fullname = a.Description,
                              amType = a.AirmenType_Id,
                              License = l.description
                          }).FirstOrDefault();
                return View(tr);
            }
            else if (Loc == "VA")
            {
                var am = db_va.tblAirmen.ToList();
                var lic = db_mnl.tblAMTypes.ToList();
                var tr = (from a in am
                          join l in lic on a.AirmenType_Id equals l.code
                          where a.Code.Equals(Id)
                          select new TestReportStatusViewModel
                          {
                              Id = a.Code,
                              PEL = a.PEL,
                              Fullname = a.Description,
                              amType = a.AirmenType_Id,
                              License = l.description
                          }).FirstOrDefault();
                return View(tr);
            }
            else if (Loc == "MA")
            {
                var am = db_ma.tblAirmen.ToList();
                var lic = db_mnl.tblAMTypes.ToList();
                var tr = (from a in am
                          join l in lic on a.AirmenType_Id equals l.code
                          where a.Code.Equals(Id)
                          select new TestReportStatusViewModel
                          {
                              Id = a.Code,
                              PEL = a.PEL,
                              Fullname = a.Description,
                              amType = a.AirmenType_Id,
                              License = l.description
                          }).FirstOrDefault();
                return View(tr);
            }
            else
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        public ActionResult Initial(TestReportStatusViewModel testReports)
        {
            var username = Session["Username"].ToString();
            if (username == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var tr = new tblTestReportApplication
            {
                //Description = testReport.Fullname,

                PEL = testReports.PEL,
                amType = testReports.amType,
                Status = "Initial",
                Initial = username,
                iDate = DateTime.Now,
                Remarks = testReports.Remarks,
                LastModifiedBy = username,

                //set date for NOT NULL datetime fields
                cDate = DateTime.Now,
                rDate = DateTime.Now,
                pDate = DateTime.Now,
                Received = DateTime.Now


            };



            db_mnl.tblTestReportApplications.Add(tr);
            db_mnl.SaveChanges();

            return RedirectToAction("ViewApplications");




        }

        public ActionResult Control(int Id, string PEL)
        {
            var username = Session["Username"].ToString();
            if (username == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var am = db_mnl.getAirmen_all(PEL).ToList();
            var trList = db_mnl.tblTestReportApplications.ToList();
            var lic = db_mnl.tblAMTypes.ToList();
            var tr = (from t in trList
                      join l in lic on t.amType equals l.code
                      join a in am on t.PEL equals a.PEL
                      where t.Id.Equals(Id)
                      select new TestReportStatusViewModel
                      {
                          Id = t.Id,
                          PEL = t.PEL,
                          Fullname = a.Fullname,
                          amType = t.amType,
                          License = l.description,
                          Remarks = t.Remarks

                      }).FirstOrDefault();
            return View(tr);
        }

        [HttpPost]
        public ActionResult Control(TestReportStatusViewModel testReports, int Id)
        {
            var username = Session["Username"].ToString();
            var tr = new tblTestReportApplication
            {
                //Description = testReport.Fullname,
                Status = "Controlled",
                BatchNo = testReports.BatchNo,
                ControlNo = testReports.ControlNo,
                ControlledBy = username,
                cDate = DateTime.Now,
                Remarks = testReports.Remarks,
                LastModifiedBy = username,

            };


            tblTestReportApplication trToEdit = db_mnl.tblTestReportApplications.Find(Id);

            trToEdit.Status = tr.Status;
            trToEdit.ControlNo = tr.ControlNo;
            trToEdit.ControlledBy = tr.ControlledBy;
            trToEdit.BatchNo = tr.BatchNo;
            trToEdit.cDate = tr.cDate;
            trToEdit.Remarks = tr.Remarks;
            trToEdit.LastModifiedBy = tr.LastModifiedBy;

            if (trToEdit.BatchNo == null || trToEdit.ControlNo == null)
            {
                ModelState.AddModelError("notNull", "Batch No and Control No cannot be empty.");
                ViewBag.ErrorMsg = "Batch No and Control No cannot be empty.";
            }
            else
            {

AEBSystem/AEBSystem.WebUI/Views/TRTracking/BatchProcess.cshtml
@model AEBSystem.Core.Models.BatchProcessModel
@using AEBSystem.Core.Models
@{
    ViewBag.Title = "Batch Process";
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox-content">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Test Report Batch Processing</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.BatchNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.BatchNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BatchNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.DropDownList("Status", new SelectList(Enum.GetValues(typeof(BatchProcessDropDown))),
                                  "--Select Status--",
                                  new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "ViewApplications")
        </div>
    </div>
</div>

AEBSystem/AEBSystem.WebUI/Views/TRTracking/Control.cshtml
@model AEBSystem.Core.ViewModels.TestReportStatusViewModel

@{
    ViewBag.Title = "Control";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <h2><strong>Control</strong></h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">


    <div class="ibox-content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.PEL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PEL, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.PEL, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.amType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.amType, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.amType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.License, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.License, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.License, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BatchNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BatchNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BatchNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ControlNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ControlNo, new { htmlAttributes = new { @class = "form-control" } })
                        <h4 class="text-danger">@ViewBag.ErrorMsg</h4>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                    </div>
                </div>

                

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "ViewApplications")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AEBSystem/AEBSystem.WebUI/Views/TRTracking/Details.cshtml
@model AEBSystem.Core.ViewModels.HistoryViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Exam History</h2>
<div class="col-md-2">
    <h3>Subject</h3>
    @*<div class="list-group">
       @foreach (var subj in Model.History)
       {
        <strong class="label label-default">@subj.Subject</strong>
       }
    </div>*@
</div>



<table class="table table-striped">
   
    @Html.ActionLink("Back to List", "Index")

    @foreach (var item in Model.History)
    {

        {
            var cssClass = "";
            if (item.PassFail == "Failed")
            {
                cssClass = "label label-danger";
            }
            else if (item.PassFail == "Passed")
            {
                cssClass = "label label-success";
            }
            else
            {
                cssClass = "label label-warning";
            }

            <tr>

                <td>
                    <span class="@cssClass"> @Html.DisplayFor(modelItem => item.Subject)</span>
                </td>

                <td>
                    <span class="@cssClass">@Html.DisplayFor(modelItem => item.PassFail)</span>
                </td>
                <td>
                    <span class="@cssClass">@Html.DisplayFor(modelItem => item.Rating)</span>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.exam_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Applicant_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correct_Ans)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.No_Items)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Loc)
                </td>
            </tr>

        }


    }


</table>

AEBSystem/AEBSystem.WebUI/Views/TRTracking/Index.cshtml
@model IEnumerable<AEBSystem.Core.Models.getAirmenAll>


@{
            ViewBag.Title = "Airmen Informations";
}

<div class="wrapper wrapper-content animated fadeInRight">
    

   
    <div class="ibox-content">
        @using (Html.BeginForm("Index", "TRTracking", FormMethod.Get))
        {
            <div class="row">
                <div class="col-sm-6">
                    
                    <h3>Search Airmen</h3>
                    
                </div>
                <div class="col-sm-6">

                    <div class="input-group">
                        @*<input type="text" placeholder="Search" class="input-sm form-control"/>*@
                        @Html.TextBox("search", null, new { @class = "input-sm form-control", @placeholder = "Search PEL or Fullname"})<span class="input-group-btn">
                            <input type="submit" name="submit" value="Search" class="btn btn-sm btn-primary" />
                        </span>
                    </div>
                </div>
            </div>
        }
        <hr />
        <table class="table  table-striped">
            <tr>
                <th>Actions</th>
                <th>
                    @Html.DisplayNameFor(model => model.PEL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fullname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AirmenType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Airmen_Desc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Loc)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <td>
                       
                        @Html.ActionLink("Details", "Initial",  new { Id = item.recid, Loc = item.Loc.Trim()}, new { @class = "btn btn-sm btn-outline btn-success", @role = "button" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PEL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fullname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AirmenType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Airmen_Desc)
                    </td>
                    <td>@{
                        var cssClass = "";
                        if (item.Loc.Contains("MNL"))
                        {
                            cssClass = "label label-success";
                        }
                        else if (item.Loc.Contains("NLA"))
                        {
                            cssClass = "label label-primary";
                        }
                        else if (item.Loc.Contains("VA"))
                        {
                            cssClass = "label label-warning";
                        }
                        else
                        {
                            cssClass = "label label-danger";
                        }
                        <span class="@cssClass">@Html.DisplayFor(modelItem => item.Loc)</span>
                    }


                       
                    </td>
                   
                </tr>
            }

        </table>
    </div>
</div>

AEBSystem/AEBSystem.WebUI/Views/TRTracking/Initial.cshtml
@model AEBSystem.Core.ViewModels.TestReportStatusViewModel

<div class="row wrapper border-bottom white-bg page-heading">

    @{
        ViewBag.Title = "Initial Application";
    }

    <h2><strong>Initial Application</strong></h2>



</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox-content">
        @using (Html.BeginForm("Initial", "TRTracking", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Airmen Informations</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.PEL, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.PEL, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.PEL, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.amType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.amType, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.amType, "", new { @class = "text-danger" })
                    </div>
                </div>
                    
                <div class="form-group">
                    @Html.LabelFor(model => model.License, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.License, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.License, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                    </div>
                </div>

              

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @*@Html.ActionLink("History", "ExamHistory", new { PEL = Model.PEL, amType = Model.amType }, new { @class = "btn btn-sm btn-success", @role = "button" }) |*@
            @Html.ActionLink("Back to List", "Index") | 
            @Html.ActionLink("History", "ExamHistory", new { PEL = Model.PEL, amType = Model.amType })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AEBSystem/AEBSystem.WebUI/Views/TRTracking/ViewApplications.cshtml
@model IEnumerable<AEBSystem.Core.ViewModels.TestReportStatusViewModel>



    @{
        ViewBag.Title = "Test Report Status";
    }

   




<div class="wrapper wrapper-content animated fadeInRight">


    <div class="ibox-content">
        @using (Html.BeginForm("ViewApplications", "TRTracking", FormMethod.Get))
        {

        <div class="row">
            <div class="col-sm-6">

                <h3>View Test Report Applications</h3>

            </div>

            <div class="col-sm-6">
                <div class="input-group">
                    @*<input type="text" placeholder="Search" class="input-sm form-control"/>*@
                    @Html.TextBox("search", null, new { @class = "input-sm form-control" })<span class="input-group-btn">
                        <input type="submit" name="submit" value="Search" class="btn btn-sm btn-primary" />
                    </span>
                </div>
            </div>
        </div>
        }
        <hr />

        <table class="table">
            <tr>
                <th>
                    Tag as
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PEL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fullname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.License)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Remarks)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BatchNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ControlNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClaimedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastModifiedBy)
                </th>
               
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink("Details", "TestReportStatusFullView", new { Id = item.Id, PEL = item.PEL }, new { @class = "btn btn-sm btn-outline btn-default", @role = "button" }) | 
                        @{                           
                            if (item.Status.Contains("Initial"))
                            {
                                @Html.ActionLink("Control", "Control", new { Id = item.Id, PEL = item.PEL }, new { @class = "btn btn-sm btn-outline btn-success", @role = "button" })
                            }
                            
                            else if (item.Status.Contains("Recieved"))
                            {
                                @Html.ActionLink("Release", "Release", new { Id = item.Id, PEL = item.PEL }, new { @class = "btn btn-sm btn-outline btn-primary", @role = "button" })
                            }

                        }                       
                       
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PEL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fullname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.License)
                    </td>
                    <td>
                        @{
                            var cssClass = "";
                            if (item.Status.Contains("Initial"))
                            {
                                cssClass = "label label-warning";
                            }
                            else if (item.Status.Contains("Controlled"))
                            {
                                cssClass = "label label-success";
                            }
                            else if (item.Status.Contains("Pending"))
                            {
                                cssClass = "label label-danger";
                            }
                            else if (item.Status.Contains("Recieved"))
                            {
                                cssClass = "label label-primary";
                            }
                            else
                            {
                                cssClass = "label label-default";
                            }
                            <span class="@cssClass">@Html.DisplayFor(modelItem => item.Status)</span>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Remarks)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BatchNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClaimedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastModifiedBy)
                    </td>
                    
                </tr>
                            }

        </table>
    </div>
</div>